"""Add user_id to expenses

Revision ID: 582cb5fdf1aa
Revises: f7b256cdfc63
Create Date: 2025-05-06 13:49:29.238177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582cb5fdf1aa'
down_revision = 'f7b256cdfc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expenses_user_id', 'users', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
