"""Add user_id to sales

Revision ID: f7b256cdfc63
Revises: 0a6226c21158
Create Date: 2025-05-06 13:33:00.324388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b256cdfc63'
down_revision = '0a6226c21158'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('sales', schema=None) as batch_op:
        # Temporarily allow NULLs to avoid crashing on existing rows
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_user_id', 'users', ['user_id'], ['id'])



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
